[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "dirso"
version = "0.1.0"
description = "A tool to organize directories by file extensions"
readme = "README.md"
requires-python = ">=3.8"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
dirso = ["default_values.txt"]

[project.scripts]
dirso = "dirso.main:main"